obstacle:
  position:
    x: 1.0
    y: 1.0
    z: 1.0
    a: 4.0
    b: 2.0
    c: 4.0
    d: 0.0

obstacle2:
  position:
    x: 1.0
    y: 1.0
    z: 1.0
    a: 4.0
    b: -1.0
    c: 4.0
    d: 0.0

pattern: true

pattern2: true

noise:
  type: Gaussian
  active: True
  noise_mean: 20
  noise_std_deviation: 20




