obstacle:
  position:
    x: 1.0
    y: 1.0
    z: 1.0
    a: 2.0
    b: 4.0
    c: 4.0
    d: 0.0

obstacle2:
  position:
    x: 1.0
    y: 1.0
    z: 1.0
    a: 4.0
    b: -1.0
    c: 4.0
    d: 0.0

test_case: Scenario-4-baseline

world_file_name: simple_obstacle




